### ISSUE TITLE
Not secure

### ISSUE THREAD

**Issue by billwashere** [vivin/enumjs#1]
This library is not secure.

``` javascript
var Days = Enum.define("Days(sentinel, name, ordinal) {alert(\"foo\") ;}//function foo", ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]);

alert(Days.fromName("Wednesday").name()) //
```

**Comment by vivin** [comment]
Good catch - I'll put a test in there to make sure that `typeName` is a JavaScript identifier of the form `^[a-zA-Z$_][0-9a-zA-Z$_]*$`.

**Comment by vivin** [comment]
Fixed in https://github.com/vivin/enumjs/commit/45fcb2e7785e19015641e53b5e77a63bf3c7d5a2.
